"""FK changes

Revision ID: 543061488e95
Revises: dcf8878032a2
Create Date: 2026-03-10 20:21:22.625935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543061488e95'
down_revision = 'dcf8878032a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_items_cart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_cart_id_fkey'), 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###
